# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: febd138302cc85afd7fabb41801b40fee5b6496105688462c364d85bab2f3c400a746bf246d1dce4f4ad0d8a4ef5e8524301bbd5e34b2b1c0f960767e86db6fe

test:
  secret_key_base: 312a5376a30b7e0a79c1963744c996375db37931e9043e201115d574ece1f6a9328df96343a1efbf0c7cd084a424443d40bb4ef0f84fa7668c1aae312e47e768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
